### ISSUE TITLE
#1 Als Werknemer wil ik alle informatie van de vacature kunnen zien, zodat ik weet waar ik aan toe ben als ik me besluit in te schrijven

### ISSUE THREAD

**Issue by GhostyHobbit** [GhostyHobbit/TLE-Agency#3]
Acceptatiecriteria
- [x] Pagina is te bereiken vanaf de vacatures overzicht
- [x] Pagina heeft de belangrijkste informatie van een vacature
- [x] Pagina is visueel ingericht voor toegankelijkheid

Definition of Done
- [ ] De functionaliteit voldoet volledig aan de acceptatiecriteria van de user story.
- [ ] De interface en interacties zijn intuïtief en getest met gebruikers, met een focus op eenvoud en Inclusiviteit.
- [ ] De implementatie voldoet aan de WCAG 2.1-normen voor toegankelijkheid, met speciale aandacht voor gebruik door mensen met beperkingen.
- [ ] Gegevensopslag en -verwerking voldoen aan AVG-richtlijnen. Er zijn geen beveiligingslekken aanwezig volgens OWASP-top-10-standaarden.
- [ ] De interface is responsive voor mobiel en desktop. De focus ligt op mobiel.

**Comment by WesleyNederpel** [comment]
Haal nog fftjes de harcoded stukkies eruit en dan mag die van mij naar Accepted!
